name: mojtrsat
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.8.3
  flutter_riverpod: ^2.6.1
  google_sign_in: ^6.3.0
  curved_navigation_bar: ^1.0.6
  http: ^1.3.0
  html: ^0.15.5
  puppeteer: ^3.17.0
  go_router: ^14.8.1
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1
  uuid: 4.5.1
  flutter_dotenv: ^5.2.1
  dartz: ^0.10.1
  flutter_animate: ^4.5.2

  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5


flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - .env
    # Add assets from the images directory to the application.
    - assets/images/


